name: Build & push LunaTV to GHCR

on:
  schedule:
    - cron: '0 2 * * *'   # 每天 02:00 UTC
  workflow_dispatch:      # 手动按钮
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/lunatv:latest
            ghcr.io/${{ github.actor }}/lunatv:${{ github.run_number }}
